name: Build and Push Docker Images

on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Build and push dashboard image
              uses: docker/build-push-action@v2
              with:
                  context: ./dashboard
                  push: true
                  tags: cryxnet/crawnet-dashboard:${{ github.ref }}

            - name: Build and push overseen image
              uses: docker/build-push-action@v2
              with:
                  context: ./overseen
                  push: true
                  tags: cryxnet/crawnet-overseen:${{ github.ref }}
