name: Integration Test

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Start Services
              run: |
                  docker-compose up -d
                  sleep 10

            - name: Run Integration Tests
              run: python tests/integration.py

            - name: Stop Services
              run: docker-compose down
