name: Integration Test

on:
    push:
        branches: [main]

jobs:
    Testing:
        runs-on: ubuntu-latest
        env:
            NEO4J_USERNAME: neo4j
            NEO4J_PASSWORD: neo4j123
            NEO4J_CONNECTION_URI: bolt://neo4j:7687
            FLASK_APP: app.py
            FLASK_DEBUG: 1
            FLASK_APP_URL: http://localhost:5000
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Start Services
              run: |
                  docker-compose up -d
                  sleep 30

            - name: Installing PIP Packages
              run: pip install neo4j

            - name: 'Integration Test: Reach Website'
              run: cd tests && python -c "from integration  import IntegrationTestCases;IntegrationTestCases().test_reach_website()"

            - name: 'Integration Test: Reach API'
              run: cd tests && python -c "from integration  import IntegrationTestCases;IntegrationTestCases().test_reach_api()"

            - name: 'Integration Test: Reach & Connect to Neo4j'
              run: cd tests && python -c "from integration  import IntegrationTestCases;IntegrationTestCases().test_reach_neo4j()"

            - name: 'Integration Test: API and Website Communication'
              run: cd tests && python -c "from integration  import IntegrationTestCases;IntegrationTestCases().test_api_website_communication()"

            - name: 'Integration Test: API and Neo4j Communication'
              run: cd tests && python -c "from integration  import IntegrationTestCases;IntegrationTestCases().test_api_neo4j_communication()"

            - name: Stop Services
              run: docker-compose down
